### ISSUE TITLE
[Feature] 支持窗口位置记忆功能

### ISSUE THREAD

**Issue by MangMax** [Richasy/FantasyCopilot#20]
### Description

当使用这种工具类的软件时，他更多的是一种辅助，我并不想让他影响到我当前视野内的主任务，所以我更习惯以将他放置在屏幕的侧边，或者你觉得你顺手的位置。

### Solution

记录上次窗口的位置，可选打开时在屏幕中央还是上次的位置

**Comment by Richasy** [comment]
目前已经支持窗口位置记忆，将会在未来更新
