### ISSUE TITLE
[Feature] 使用本地的Embedding能力

### ISSUE THREAD

**Issue by chenrensong** [Richasy/FantasyCopilot#22]
### Description

大规模使用OpenAI或者Azure OpenAI的Embedding接口，成本太高。

### Solution

可以采用替代的方案
https://github.com/chenrensong/Embedding
https://github.com/chenrensong/SS.SemanticKernel.Extensions

**Comment by Richasy** [comment]
涉及到其它模型，理论上都可以用插件的方式解决，目前写在应用本体内可能并不是一个很好的选择。
不过我会调查你提到的两种解决方案，如果具备足够的通用性，我会尝试看如何集成它们，或者写一个插件

**Comment by Richasy** [comment]
由于 OpanAI 前段时间的更新，Embedding 的成本大幅下降，目前应用没有足够的理由探索对单一语种的 Embedding 的支持。

所以暂时关闭该 issue，如果你认为这仍是一项值得投入的事情，并期待更广泛的讨论，你可以再打开它。
