### ISSUE TITLE
[Bug] 启动时崩溃

### ISSUE THREAD

**Issue by Huang-Zifeng** [Richasy/FantasyCopilot#26]
### Bug description

初次启动时崩溃

### Reproduce steps

```plain text
1. 在微软商店下载小幻助理
2. 打开小幻助理
3. 出现如图所示的情况
```

### Expected behavior

出现正常的画面

### Screenshot

![image](https://github.com/Richasy/FantasyCopilot/assets/110339237/e36b9463-4b8c-4c25-a8dc-764b4858a3cb)

### Application source

- [X] Microsoft Store
- [ ] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Others

### Device

Tablet

**Comment by Richasy** [comment]
你的应用圆角好像很大，你是用了什么软件吗？

**Comment by Huang-Zifeng** [comment]
> 你的应用圆角好像很大，你是用了什么软件吗？

这个是ShareX的截图效果
另外，我发现重启电脑之后软件可以正常启动了。不知道是什么原因。
如果有可以提交log的方法我可以提供。

**Comment by Richasy** [comment]
@Huang-Zifeng 我还以为是用了什么奇怪插件导致的应用渲染崩溃，很高兴听到问题已经解决，果然重启可以解决九成的问题🤣。查看log可以在设置应用里打开log文件夹，然后找到对应日期的log查看。如果有记录的话可以贴上来以便进行错误分析。
---
不过既然已经可以正常使用，那么我就先关闭这个issue了，如果后续还出现了这个问题，请随时再打开
