### ISSUE TITLE
[Bug] 生成回答的过程中，如果浏览对话历史后尝试滚动到最底部，会偶现无法滚动到最底部的情况

### ISSUE THREAD

**Issue by Vixb1122** [Richasy/FantasyCopilot#27]
### Bug description

生成回答的过程中，如果浏览对话历史后尝试滚动到最底部，会偶现无法滚动到最底部的情况。
生成回答成功之后，可以正常滚动到最底部。
一般在对话10次以上之后，出现的几率变大

### Reproduce steps

```plain text
1. 进行多次问答之后
2. 发起问题，在等待回答相应时，滚动浏览历史
3. 尝试滚动到底部
```

### Expected behavior

1. 列表可以正常滚动

### Application source

- [X] Microsoft Store
- [ ] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Others

### Device

Desktop

**Comment by Huang-Zifeng** [comment]
I have the same issue.

**Comment by Richasy** [comment]
我使用了新的列表控件，表现稳定一些，但是内存占用略有上涨。下次更新时发布，你可以在更新后再进行尝试
