### ISSUE TITLE
[Feature] Improve openai proxy services

### ISSUE THREAD

**Issue by JadynWong** [Richasy/FantasyCopilot#33]
### Description

To support the Proxy OpenAI service, a lot of SK's redundant code has been copied. We can use OpenAI proxy services in a more concise way. 

### Solution

We can use `HttpClient`'s `HttpMessageHandler` to intercept and override the OpenAI address as the proxy address.

### Additional

https://github.com/microsoft/semantic-kernel/issues/1445#issuecomment-1590980113

**Comment by Richasy** [comment]
Great advice! Thank you very much for your help!
