### ISSUE TITLE
不支持win10 是吗

### ISSUE THREAD

**Issue by 839781960** [Richasy/FantasyCopilot#36]
### Bug description

不支持win10 是吗

### Reproduce steps

```plain text
不支持win10 是吗
```

### Expected behavior

不支持win10 是吗

### Application source

- [X] Microsoft Store
- [ ] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Others

### Device

Desktop

**Comment by Richasy** [comment]
是的

**Comment by Richasy** [comment]
@PaTTeeL 你的 Win10 是什么版本的？另外 LTSC 可能跑不起来 Windows App SDK 应用

**Comment by PaTTeeL** [comment]
> @PaTTeeL 你的 Win10 是什么版本的？另外 LTSC 可能跑不起来 Windows App SDK 应用

版本：Windows 10 IoT 企业版 LTSC
版本号：21H2
操作系统内部版本：19044.3086
体验：Windows Feature Experience Pack 1000.19041.1000.0

装了以下几个package，UWP正常使用中（包括Bili.Uwp）：
Microsoft.DesktopAppInstaller
Microsoft.StorePurchaseApp
Microsoft.WindowsStore
Microsoft.NET.Native.Framework
Microsoft.NET.Native.Runtime
Microsoft.VCLibs.140.00.UWPDesktop
Microsoft.VCLibs.140.00

**Comment by Richasy** [comment]
@PaTTeeL Win10 的支持不是目前的优先事项，不过在处理完开源模型集成之后，有时间我会看看。如果不需要耗费太多精力就可以适配，那就做。不然可能还是会放弃

**Comment by PaTTeeL** [comment]
> @PaTTeeL Win10 的支持不是目前的优先事项，不过在处理完开源模型集成之后，有时间我会看看。如果不需要耗费太多精力就可以适配，那就做。不然可能还是会放弃

感谢大佬！

**Comment by 96bearli** [comment]
> @PaTTeeL Win10 的支持不是目前的优先事项，不过在处理完开源模型集成之后，有时间我会看看。如果不需要耗费太多精力就可以适配，那就做。不然可能还是会放弃

之幻大佬 是时候了QWQ
