### ISSUE TITLE
[Feature] 标记创建失败的知识库，释放db文件占用

### ISSUE THREAD

**Issue by Vixb1122** [Richasy/FantasyCopilot#38]
### Description

1. 部分知识库会出现创建失败的情况，希望可以对其进行标记。以便重新导入之类的操作
2. 删除展示库时，如果尝试删除对应的db文件，会提示占用，希望可以在删除知识库时取消占用。

### Solution

1. 标记失败知识库
2. 删除知识库时，取消占用对应文件

**Comment by Richasy** [comment]
你预期的标记是什么样的？
目前应用在导入失败时会提醒用户具体的失败文件数量。同时用户也可以查看日志来获取详细信息。
我不确定你说的标记是什么意思

**Comment by Vixb1122** [comment]
创建知识库的时间可能很长，放在后台运行，可能会错过失败提醒，并不知道导入失败了。所以希望增加一个标记，避免在尝试对话之后才发现没导入成功。
