### ISSUE TITLE
需要全局开启VPN吗

### ISSUE THREAD

**Issue by minjac** [Richasy/FantasyCopilot#52]
### Bug description

你好，需要全局开启VPN吗？我使用虚拟机进行安装，能上谷歌，但是小幻用不了

### Reproduce steps

```plain text
1、在虚拟机上安装win11和小幻
2、开启全局代理
3、小幻服务不响应
```

### Expected behavior

成功返回聊天内容

### Application source

- [ ] Microsoft Store
- [ ] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Others

**Comment by Richasy** [comment]
具体是怎么不响应，有截图吗？是否按照wiki中的服务配置章节正确地配置了模型名称等信息？

**Comment by minjac** [comment]
> 具体是怎么不响应，有截图吗？是否按照wiki中的服务配置章节正确地配置了模型名称等信息？

非常感谢，按照您的指引，现在可以正常使用了。软件非常漂亮而且扎实，学习了
