### ISSUE TITLE
[Bug] 托盘图标是没了吗？

### ISSUE THREAD

**Issue by Vixb1122** [Richasy/FantasyCopilot#58]
### Bug description

勾选关闭时隐藏，关闭后在系统托盘找没到托盘图标

### Reproduce steps

```plain text
1. 勾选关闭时隐藏
2. 关闭面板
```

### Expected behavior

点击托盘图标重新打开面板

### Screenshot

![image](https://github.com/Richasy/FantasyCopilot/assets/17810492/111bcbf4-9915-4f17-bc2b-b306dacc8104)

### Application source

- [X] Microsoft Store
- [ ] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Others

### Device

Desktop

**Comment by Richasy** [comment]
这个需要重启下应用
