### ISSUE TITLE
[Bug] OpenAI 代理无法正常工作

### ISSUE THREAD

**Issue by mmcer** [Richasy/FantasyCopilot#62]
### Bug description

在设置了自定义代理后，发现无法使用 openAI 服务。
B 站的介绍视频，对于代理设置这里是一句话带过。
估计可行的是，操作系统设置全局代理，然后软件设置里留空。但这意味着放弃了软件本身的代理设置。

### Reproduce steps

```plain text
1、进入设置界面，设置 openAI 的可选代理
2、切换到对话框界面，输入文字
3、界面返回 400 错误提示
4、再次重试，问题依旧
5、界面也提示下载模型失败
```

### Expected behavior

期待是软件里设置代理后，app 可以正常使用。

经过尝试:
KernelService.cs 里，重载了SendAsync ，如果设置了代理，这里就直接修改了 URL 地址，导致失败。

一种解决方式，对于 KernelService.cs 文件：
1、移除ProxyOpenAIHandler 这个类
2、（可选）AddOpenAIService 这个方法里，判断了 hasCustomEndpoint 如果设置了代理地址，但是格式不对，是不是 UI 给个提示，或者在设置界面里输入时就判断。
3、这里是关键，AddOpenAIService 这个方法里，修改 customHttpClient 的初始化逻辑，同步调整为 var customHttpClient = hasCustomEndpoint ? new HttpClient(new HttpClientHandler { Proxy = new WebProxy(customEndpoint) }) : default;  
也就是说，这里简单设置 Proxy 为自定义的代理地址即可，不需要第一步里的类
4、GetSupportModelsAsync()这个方法里尝试去下载模型数据，由于未设置代理，会导致下载失败，可以修改为 
        client = new HttpClient(new HttpClientHandler{ Proxy = new WebProxy(_settingsToolkit.ReadLocalSetting(SettingNames.OpenAICustomEndpoint, string.Empty)) });
需要说明的是，原始代码里，client 是给 Azure 和 OpenAI 共用的，所以这里要看看怎么搞，对于 OpenAI 从配置里读。

### Application source

- [ ] Microsoft Store
- [ ] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Others

### Remark

很抱歉以 issue 的方式来描述，实在是水平太次了，无法以 PR 的方式贡献代码。

**Comment by Richasy** [comment]
想问一下，你说的代理是那种翻墙的代理吗？

应用中的OpenAI代理是类似
https://www.openai-proxy.com 的服务代理。

你可以进入上面的网站按照说明填写应用内的字段，看看是否可以生效

**Comment by mmcer** [comment]
根据 @Richasy 的描述，有点明白代码里为啥使用 URL 替换的意思了。我自己开始理解的是一个类似本地代理的方式，不会因为使用软件而依赖外部。

感谢解释，多谢。
