### ISSUE TITLE
[Bug] 解决方案Configuration 错误

### ISSUE THREAD

**Issue by mmcer** [Richasy/FantasyCopilot#63]
### Bug description

启动项目后，VS 提示 “Current solution contains incorrect configurations mappings. It may cause projects to not work correctly” 

### Reproduce steps

```plain text
1、签出项目
2、VS 2022 打开解决方案
3、VS 提示配置错误
4、配置管理器里，切换 Service.Desktop 为 Any CPU 无效
```

### Expected behavior

1、针对 AnyCPU 架构，所有的项目均配置为 AnyCPU，无论是 Debug，还是 Release
2、针对 x64 架构，所有的项目均配置为 x64，无论是 Debug，还是 Release
3、App 项目的 PublishProfiles 目录下，新增一个win10-AnyCPU.pubxml，以解决 AnyCPU 架构无法发布的问题
4、App 项目的 PublishProfiles 目录下，修改 launchSettings.json 文件，移除里面的 Remote 调试相关信息。这一项猜测似乎是作者的本地调试使用产生。
5、（可选）项目里都使用 .net 7 了，建议是否可以升级项目里的一些 .netcore 的项目，尽量保持技术栈的统一，可以少安装一些 SDK 包。

Service.Desktop 的项目文件似乎有点问题，无法基于 x64 生成 AnyCPU 后切换成功。以前碰到过类似的现象，不知道是不是 VS 的问题。

### Application source

- [ ] Microsoft Store
- [X] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Others

### Remark

根据目前掌握的信息看，无论是 win10 还是 win11，除非刻意，普通用户几乎没有机会使用 x86 架构的系统的了，买回来的电脑基本都是64位的系统。看起来作者是时代弄潮儿，所以建议考虑移除x86的配置项，以保持项目简洁，纯建议。

**Comment by Richasy** [comment]
首先，该项目是一个WindowsAppSDK项目。这种项目类型不支持AnyCPU，必须要设定架构类型才能编译，所以推荐使用x64进行编译。

其次，启动项目是App，所以只需要把App设置为启动项目，并把配置调整为x64即可编译运行。其他的类库项目可以设置架构，也可以不设置。

所以这应该不是一个需要解决的问题

**Comment by mmcer** [comment]
感谢解释，多谢。
