### ISSUE TITLE
[Feature] 希望可以配置自定义HTTP/HTTPS/SOCKS软件代理

### ISSUE THREAD

**Issue by 96bearli** [Richasy/FantasyCopilot#73]
### Description

目前软件采用仅openAI API代理的方式，我通过cloudflare和自定义域名进行达到了此访问的目的。
But：提示词库的在线获取仍然无法访问，其他有网络访问困难的服务也无法调用。
PS：不单独提issue了，希望支持自定义Prompt提示词。

### Solution

配置自定义HTTP/HTTPS/SOCK软件代理，涉及网络请求的全部使用代理。

### Plan B

为每一种服务增加自定义API代理 QWQ

**Comment by Richasy** [comment]
应用可能不会单独为网络提供代理（翻墙），实际上，如果你本地在运行一些VPN软件，比如Clash，那么应用不需要做什么额外的事情，你唯一要做的可能就是打开应用的本地网络环回的功能。

你可以在我的另一个应用：[网络回环管理器](https://www.microsoft.com/store/productid/9NTJ6CX698CL?ocid=pdpshare) 里找到小幻助理，并勾选，然后保存状态即可。

---

另外，自定义提示词的功能已经存在，在提示与会话->星标提示词，界面右侧有一个 `+` ，点击就能创建自定义提示词了
