### ISSUE TITLE
商店页面打不开了，Store里也搜索不到了

### ISSUE THREAD

**Issue by mrhan1993** [Richasy/FantasyCopilot#81]
RT

**Comment by balthild** [comment]
大概是被下架了，希望能提供离线安装的 appx

**Comment by Richasy** [comment]
因为应用名称不合规，被下架了，目前正在联系商店团队，这周应该可以重新上架

**Comment by mrhan1993** [comment]
> 因为应用名称不合规，被下架了，目前正在联系商店团队，这周应该可以重新上架

ok

**Comment by HKMV** [comment]
没有安装按钮呀
![image](https://github.com/Richasy/FantasyCopilot/assets/26456469/3c687e15-cff1-4d70-94f2-ae24a9e47e35)
